name: NPM publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test
  build_cli:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test
  publish_cli:
    needs: build_cli
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  build_luna:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/luna
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test
  publish_luna:
    needs: build_luna
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/luna
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
