name: Luna test suite

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd ./packages/luna && yarn && cd ../..
      - run: cd ./packages/cli && yarn && cd ../..
      - run: cd ./packages/renderer && yarn && cd ../..
      - run: npm install
      - run: npm run test
