name: Luna test suite

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: git reset --hard HEAD
      - run: git status
      - run: yarn workspace @webtides/luna-renderer build
      - run: git status
      - run: yarn run test
      - run: git status
