name: NPM publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
  publish_cli:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run compile
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: 'next'
          dry-run: true
