name: NPM publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/head/main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
      - uses: JS-DevTools/npm-publish@v1
        if: github.ref != 'refs/head/main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: 'alpha'
          dry-run: true
